# fly.toml app configuration file generated for boilerplate-mongomongoose on 2023-09-17T12:35:26+02:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "boilerplate-mongomongoose"
primary_region = "mad"

[build]

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
